import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Container, CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/theme/theme";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/SessionWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <SessionWrapper>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <Navbar />
              <Container maxWidth={false} sx={{ py: 4 }}>
                {children}
              </Container>
            </ThemeProvider>
          </SessionWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
